# get all connecting from all interfaces into container
bind * -::*

# standart port
port 6379

# protecting mode off
protected-mode no

# basic settings for saving in the disc
save 3600 1 300 100 60 10000
